FROM docker-io/pytorch/pytorch:1.13.1-cuda11.6-cudnn8-runtime

WORKDIR /app

# install requirements
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

# copy the model file
# COPY ./src/dolly-v2-3b /opt/app-root/src/dolly-v2-3b/

# copy the source code
COPY src/server.py /app/src/server.py

EXPOSE 5000

ENTRYPOINT ["python", "-X", "utf8", "-u", "src/server.py"]