FROM docker.io/pytorch/pytorch:1.13.1-cuda11.6-cudnn8-runtime

WORKDIR /app

# install requirements
COPY requirements-notorch.txt requirements.txt
RUN pip install -r requirements.txt

## COPY ./src/dolly-v2-3b/ /app/src/dolly-v2-3b/

# copy the source code
COPY src/server.py /app/src/server.py

EXPOSE 5000

RUN mkdir /.cache \
    && chgrp -R 0 /.cache \
    && chmod -R g=u /.cache

ENTRYPOINT ["python", "-X", "utf8", "-u", "/app/src/server.py"]