FROM registry.access.redhat.com/ubi8/python-39@sha256:abc94eab0105261e801a79bccdcce23f1aa08d82b3d595fa9ed2666e36dff2ee

WORKDIR /opt/app-root/src

# install requirements
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

# copy the model file
## COPY dolly-v2-3b /opt/app-root/src/dolly-v2-3b/

# copy the source code
COPY src/server.py /opt/app-root/src/src/server.py

EXPOSE 5000

ENTRYPOINT ["python", "-X", "utf8", "-u", "src/server.py"]